-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: v1.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: safety
        name: safety
        entry: safety check -r
        language: system
        files: requirements.txt
    -   id: pycodestyle
        name: pycodestyle
        entry: pycodestyle
        language: system
        exclude: ^migrations/
        types:
        - python
    -   id: isort
        name: isort
        entry: isort
        language: system
        exclude: ^migrations/
        types:
        - python
    -   id: pylint
        name: pylint
        entry: pylint --jobs=2
        language: system
        exclude: ^migrations/
        types:
        - python
    -   id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: python
        files: \.py$
